# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zthJbRDUYOoiwUWOdkaRDlV_0F6pZhfh
"""

import pandas as pd
baza ={
    "FISH":["valiyeva ruxshona ", "nabiyeva dildora ", "aliyeva durdona ","nabiyev dilshod","abdullayeva sabina ","baxromova aziza "      ],
    "Yoshi":["13","15","12","17","16","14"      ],
    "jinsi":[ "qiz bola","qiz bola","qiz bola","ogil bola","qiz bola","qiz bola"     ],
    "Maktab raqami  ":[  "1","2","2","68","26","68"     ]

}
df=pd.DataFrame(baza)
print(df)
df.to_excel("baza.xlsx")

filtr =df.loc[df["jinsi"]=="qiz bola"]
print (filtr)

filtr =df.loc[df["jinsi"]=="ogil bola"]
print (filtr)